# encoding: UTF-8
require 'squish'

include Squish

def main
  startApplication("addressbook")
  activateItem(waitForObjectItem(":Address Book_QMenuBar", "File"))
  activateItem(waitForObjectItem(":Address Book.File_QMenu", "Open..."))
  clickButton(waitForObject(":Address Book - Choose File.detailModeButton_QToolButton"))
  waitForObjectItem(":stackedWidget.treeView_QTreeView", "MyAddresses\\.adr")
  clickItem(":stackedWidget.treeView_QTreeView", "MyAddresses\\.adr", 112, 9, 0, Qt::LEFT_BUTTON)
  clickButton(waitForObject(":Address Book - Choose File.Open_QPushButton"))
  waitForObjectItem(":Address Book - MyAddresses.adr.File_QTableWidget", "1/1")
  clickItem(":Address Book - MyAddresses.adr.File_QTableWidget", "1/1", 45, 19, 0, Qt::LEFT_BUTTON)
  table = waitForObject(":Address Book - MyAddresses.adr.File_QTableWidget")
  Test.verify(table.rowCount == 125)
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr_QMenuBar", "Edit"))
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr.Edit_QMenu", "Add..."))
  type(waitForObject(":Forename:_LineEdit"), "Jane")
  type(waitForObject(":Forename:_LineEdit"), "<Tab>")
  type(waitForObject(":Surname:_LineEdit"), "Doe")
  type(waitForObject(":Surname:_LineEdit"), "<Tab>")
  type(waitForObject(":Email:_LineEdit"), "jane.doe@nowhere.com")
  type(waitForObject(":Email:_LineEdit"), "<Tab>")
  type(waitForObject(":Phone:_LineEdit"), "555 123 4567")
  clickButton(waitForObject(":Address Book - Add.OK_QPushButton"))
  waitForObjectItem(":Address Book - MyAddresses.adr.File_QTableWidget", "3/1")
  clickItem(":Address Book - MyAddresses.adr.File_QTableWidget", "3/1", 44, 14, 0, Qt::LEFT_BUTTON)
  type(waitForObject(":Address Book - MyAddresses.adr.File_QTableWidget"), "<Shift>")
  type(waitForObject(":Address Book - MyAddresses.adr.File_QTableWidget"), "D")
  type(waitForObject(":Address Book - MyAddresses.adr.3_1_LineEdit"), "oe")
  type(waitForObject(":Address Book - MyAddresses.adr.3_1_LineEdit"), "<Return>")
  waitForObjectItem(":Address Book - MyAddresses.adr.File_QTableWidget", "0/1")
  Test.verify(table.rowCount == 126)
  clickItem(":Address Book - MyAddresses.adr.File_QTableWidget", "0/1", 9, 20, 0, Qt::LEFT_BUTTON)
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr_QMenuBar", "Edit"))
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr.Edit_QMenu", "Remove..."))
  clickButton(waitForObject(":Address Book - Delete.Yes_QPushButton"))
  Test.verify(table.rowCount == 125)
  waitFor("Squish::Object.exists(':File.0_0_QModelIndex')", 20000)
  Test.compare(findObject(":File.0_0_QModelIndex").text, "Jane")
  waitFor("Squish::Object.exists(':File.0_1_QModelIndex')", 20000)
  Test.compare(findObject(":File.0_1_QModelIndex").text, "Doe")
  waitFor("Squish::Object.exists(':File.0_2_QModelIndex')", 20000)
  Test.compare(findObject(":File.0_2_QModelIndex").text, "jane.doe@nowhere.com")
  waitFor("Squish::Object.exists(':File.0_3_QModelIndex')", 20000)
  Test.compare(findObject(":File.0_3_QModelIndex").text, "555 123 4567")
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr_QMenuBar", "File"))
  activateItem(waitForObjectItem(":Address Book - MyAddresses.adr.File_QMenu", "Quit"))
  clickButton(waitForObject(":Address Book - Delete.No_QPushButton"))
end
